### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by llllearner** [ratishsp/data2text-seq-plan-py#1]
https://github.com/ratishsp/data2text-seq-plan-py/blob/101d99032f67d302b5c19e8c6ed820cb1af6de25/scripts/create_mlb_target_data.py#L12

**Comment by ratishsp** [comment]
Hi, the script to create the formatted version of mlb dataset requires huggingface datasets installation. You could try `pip install datasets`. BTW this library is only needed for preprocessing and not during training of models. So you could also do this in a separate conda environment.

**Comment by llllearner** [comment]
> Hi, the script to create the formatted version of mlb dataset requires huggingface datasets installation. You could try `pip install datasets`. BTW this library is only needed for preprocessing and not during training of models. So you could also do this in a separate conda environment.

OK, thanks for your answer.
