### ISSUE TITLE
Where is `traintokens-ordinaladjective-inning-identifier`

### ISSUE THREAD

**Issue by Ber666** [ratishsp/data2text-seq-plan-py#2]
Hi, I tried to reproduce the experiements following the instruction, but it seems the file `traintokens-ordinaladjective-inning-identifier` is missing..

**Comment by Ber666** [comment]
OK, I think I've found those files [here](https://drive.google.com/drive/folders/19u99YQqoG7K4xIq9XdeZgPGr2jvQSCIe). Maybe making this clear in README would help others : )

**Comment by ratishsp** [comment]
Sorry about that. Addressed in https://github.com/ratishsp/data2text-seq-plan-py/commit/26dc6f699a5464cdb8b21144c3617691e4b0255d.
